# Generated by Django 4.2.7 on 2023-11-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0002_alter_contactcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='category',
        ),
        migrations.AddField(
            model_name='contactcategory',
            name='prospect',
            field=models.ManyToManyField(to='sdr.prospect'),
        ),
    ]
