# Generated by Django 4.2.7 on 2023-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0003_remove_prospect_category_contactcategory_prospect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcategory',
            name='prospect',
        ),
        migrations.AddField(
            model_name='prospect',
            name='category',
            field=models.ManyToManyField(to='sdr.contactcategory'),
        ),
    ]
