# Generated by Django 4.2.7 on 2023-11-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0004_rename_campaign_generated_email_aigeneratedemail_campaign_generated_email_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigeneratedemail',
            name='campaign',
        ),
    ]
