# Generated by Django 4.2.7 on 2023-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0005_contacts_remove_campaign_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
