# Generated by Django 4.2.7 on 2023-11-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0005_remove_aigeneratedemail_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigeneratedemail',
            name='campaign_identifier',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='aigeneratedemail',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aigeneratedemail',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdr.campaign'),
        ),
    ]
