# Generated by Django 4.2.7 on 2023-11-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0006_remove_aigeneratedemail_campaign_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigeneratedemail',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='campaign',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
