# Generated by Django 4.2.7 on 2023-12-02 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0007_remove_aigeneratedemail_prospect_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='contacts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sdr.contacts'),
            preserve_default=False,
        ),
    ]
