# Generated by Django 4.2.7 on 2023-11-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0008_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
